services:
  - type: web
    name: egyptian-stock-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt && pip install git+https://github.com/egxlytics/egxpy.git
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
